import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'

import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from 'next-themes'

import { TranslationsProvider } from '@/bookly/providers'
import type { PageProps } from '@/bookly/types'
import { ThemeChanger } from '@/bookly/components/temporary'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode
  params: PageProps['params']
}>) {
  const { lang: locale } = await params

  return (
    <TranslationsProvider locale={locale}>
      <ThemeProvider attribute='class' enableSystem>
        <ThemeChanger />
        <div
          style={{
            background: 'var(--background)',
            color: 'var(--foreground)',
            fontFamily: 'Arial, Helvetica, sans-serif'
          }}
          className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
        >
          {children}
        </div>
      </ThemeProvider>
    </TranslationsProvider>
  )
}
